# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9db355888f27c083071def35f3a1c226"
name = "testing-react-extension"
handle = "testing-react-extension"
application_url = "https://fonts-babies-nsw-trained.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://fonts-babies-nsw-trained.trycloudflare.com/auth/callback",
  "https://fonts-babies-nsw-trained.trycloudflare.com/auth/shopify/callback",
  "https://fonts-babies-nsw-trained.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://fonts-babies-nsw-trained.trycloudflare.com/api/proxy"
subpath = "recommendations"
prefix = "apps"

[pos]
embedded = false
